version: '3'
services:
  app:
    # image: php:8.1
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    volumes:
      - ./task_management_app:/work/task_management_app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work/task_management_app
    ports:
      - 8000:8000
    command: sh -c "composer install && composer update && php artisan serve --host 0.0.0.0"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - LANG=${LANG}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: